version: '3.9'

services:
  postgres:
    build:
      dockerfile: Dockerfile.pg
    environment:
      - POSTGRES_PASSWORD=unsafe
    expose:
      - 5432
    ports:
      - 5432:5432
  api:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile.api
    expose:
      - 80
    environment:
      - HOST=0.0.0.0
      - PORT=80
    ports:
      - 8080:80
  site:
    depends_on:
      - api
      - postgres
    build:
      context: .
      dockerfile: Dockerfile.site
    expose:
      - 80
    ports:
      - 9090:80
