# https://taskfile.dev

version: "3"

env:
  TZ: America/New_York

tasks:
  default:
    cmds:
      - task: ci
    silent: true

  lint:
    - poetry run mypy
    - poetry run pylint --rcfile=pyproject.toml flurry.*

  test:
    - poetry run pytest -k 'not test_postgres_storage' {{.CLI_ARGS}}

  test:postgres:
    - task: postgres:start
    - defer: { task: postgres:stop }
    - sleep 5
    - poetry run pytest -k 'test_postgres_storage' {{.CLI_ARGS}}

  test:examples:
    - task: postgres:start
    - defer: { task: postgres:stop }
    - sleep 5
    - python examples/todo/test_todo.py

  ci:
    cmds:
      - |
        if [ -z "$(which poetry)" ]; then
          pip install poetry==1.1.12;
        fi
      - task: install
      - task: lint
      - task: test
      - task: test:postgres
      - task: test:examples

  for_all:
    silent: true
    cmds:
      - |
        ROOT_DIR="$(pwd)"
        for PKG_DIR in flurry.*; do
          cd "$ROOT_DIR/$PKG_DIR";
          echo -e "\n=====> in $PKG_DIR"
          {{.DO_COMMAND}}
        done

  build:
    cmds:
      - if [ ! -d "./dist" ]; then mkdir dist; fi
      - task: for_all
        vars: { DO_COMMAND: "poetry build && cp ./dist/* ../dist" }

  clean:
    cmds:
      - if [ -d "./dist" ]; then rm -rf ./dist; fi
      - task: for_all
        vars: { DO_COMMAND: "echo 'removing dist/' && rm -rf dist/" }

  install:
    - poetry install
    - task: for_all
      vars: { DO_COMMAND: "poetry install" }

  update:
    - poetry update
    - task: for_all
      vars: { DO_COMMAND: "poetry update" }

  publish:
    - task: build
    - task: for_all
      vars: { DO_COMMAND: "poetry publish" }

  postgres:build:
    - docker build --tag flurry_postgres:plpython3 - < flurry.postgres/Dockerfile.pg

  postgres:start:
    - docker run -d -t -i
      --name flurry_postgres_test
      -e POSTGRES_PASSWORD=unsafe
      -p 31415:5432
      flurry_postgres:plpython3

  postgres:stop:
    - docker rm -f flurry_postgres_test
