# https://taskfile.dev

version: "3"

env:
  TZ: America/New_York

tasks:
  default:
    - task: install
    - task: test

  install:
    - if [ -z "$(which poetry)" ]; then pip install -r requirements.txt; fi
    - poetry install

  lint:
    - mypy
    - pylint --rcfile=pyproject.toml money

  test:
    - defer: { task: postgres:stop }
    - task: postgres:start
    - echo "waiting for database"
    - sleep 2
    - echo "running tests"
    - pytest -s --log-cli-level=INFO {{.CLI_ARGS}}
    - task: lint

  postgres:build:
    - docker build --tag money_pg:plpython3 - < Dockerfile.pg

  postgres:start:
    - docker run -d -t -i
      --name money_pg_test
      -e POSTGRES_PASSWORD=unsafe
      -p 5432:5432
      money_pg:plpython3

  postgres:stop:
    - docker rm -f money_pg_test
