# https://taskfile.dev

version: "3"

env:
  TZ: America/New_York

tasks:
  lint:
    - poetry run mypy
    - poetry run pylint --rcfile=pyproject.toml fete.*

  test:
    - poetry run pytest {{.CLI_ARGS}}

  ci:
    cmds:
      - |
        if [ -z "$(which poetry)" ]; then
          pip install poetry==1.1.12;
        fi
      - task: install
      - task: lint
      - task: test

  for_all:
    silent: true
    cmds:
      - |
        ROOT_DIR="$(pwd)"
        for PKG_DIR in fete.*; do
          cd "$ROOT_DIR/$PKG_DIR";
          echo -e "\n=====> in $PKG_DIR"
          {{.DO_COMMAND}}
        done

  build:
    silent: true
    cmds:
      - task: for_all
        vars: { DO_COMMAND: "poetry build" }

  clean:
    silent: true
    cmds:
      - task: for_all
        vars: { DO_COMMAND: "rm -rf dist/" }

  install:
    - poetry install
    - task: for_all
      vars: { DO_COMMAND: "poetry install" }

  update:
    - poetry update
    - task: for_all
      vars: { DO_COMMAND: "poetry update" }

  postgres:build:
    - docker build --tag fete_postgres:plpython3 - < fete.postgres/Dockerfile.pg

  postgres:start:
    - docker run -d -t -i
      --name fete_postgres_test
      -e POSTGRES_PASSWORD=unsafe
      -p 5432:5432
      fete_postgres:plpython3

  postgres:stop:
    - docker rm -f fete_postgres_test
