# https://taskfile.dev

version: "3"

env:
  TZ: America/New_York

tasks:
  default:
    - |
      if [ ! -d ".venv" ]; then
        echo "Creating a new virtual environment @ ./.venv"
        python -m venv .venv;
        echo "Run 'source .venv/bin/activate' and then try again"
        exit 1
      fi
    - task: install
    - task: test

  install:
    - if [ -z "$(which poetry)" ]; then pip install -r requirements.txt; fi
    - poetry install

  lint:
    - mypy --config-file=pyproject.toml
    - pylint --rcfile=pyproject.toml money

  test:
    - task: lint
    - defer: { task: postgres:stop }
    - task: postgres:start
    - echo "waiting for database"
    - sleep 2
    - echo "running tests"
    - pytest -s --log-cli-level=INFO {{.CLI_ARGS}}
    - task: test:example

  test:example:
    - python examples/todo/test_todo.py

  postgres:build:
    - docker build --tag money_pg:plpython3 - < Dockerfile.pg

  postgres:start:
    - docker run -d -t -i
      --name money_pg_test
      -e POSTGRES_PASSWORD=unsafe
      -p 5432:5432
      money_pg:plpython3

  postgres:stop:
    - docker rm -f money_pg_test
