name: Build and Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code
        uses: actions/checkout@v2
      - name: set up nodejs environment
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.1"
      - name: set up python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: install the task runner
        uses: arduino/setup-task@v1
        with:
          version: 3.10.0
      - name: install dependencies
        run: task install
      - name: run tests
        run: task test
