name: CI
on: [push, pull_request]
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-18.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: check out the code
        uses: actions/checkout@v2
      - name: set up nodejs environment
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.1"
      - name: set up python environment
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: create python virtualenv
        run: python -m venv .venv
      - name: install the task runner
        uses: arduino/setup-task@v1
        with:
          version: 3.10.0
      - name: install dependencies
        run: |
          pip install poetry
          source .venv/bin/activate
          task install
          task postgres:build
      - name: run tests
        run: |
          source .venv/bin/activate
          task test
