name: Release
on:
  push:
    tags:
      - "**"
jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: check out the code
        uses: actions/checkout@v2
      - name: set up python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: create python virtualenv
        run: python -m venv .venv
      - name: install the task runner
        uses: arduino/setup-task@v1
        with:
          version: 3.10.0
      - name: install deps and run tests
        run: |
          . .venv/bin/activate
          task postgres:build
          task ci
          task build
          export GH_ACCESS_TOKEN=${{ secrets.GH_ACCESS_TOKEN}}
          python .github/releaser.py ./dist/*
